### ISSUE TITLE
No Query Results Displayed

### ISSUE THREAD

**Issue by TheAtomAnt** [microsoft/wiql-editor#30]
**Describe the bug**
When using the Wiql Playground, after entering a query, and pressing run, the Loading workitems... message never disappears and the query results never display.

**Environment:**
 - Browser: Chrome
 - Azure Devops

**To Reproduce**
Run any query in Wiql Playground

**Expected behavior**
I would expect to see the query results

** detail **
I noticed this error in Chrome Dev Tools:
reactProdInvariant.js:29 Uncaught (in promise) Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BdisplayName%2C%20url%2C%20_links%2C%20id%2C%20uniqueName%2C%20imageUrl%2C%20descriptor%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:401053)
    at traverseAllChildrenImpl (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:403430)
    at traverseAllChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:403591)
    at Object.instantiateChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:317802)
    at ReactDOMComponent._reconcilerInstantiateChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:363042)
    at ReactDOMComponent.mountChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:363245)
    at ReactDOMComponent._createInitialChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:334878)
    at ReactDOMComponent.mountComponent (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:333014)
    at Object.mountComponent (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:367338)
    at ReactDOMComponent.mountChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.68/1702402299665/dist/playground.js:2:363381)
ms-devlabs.wiql-editor.wiql-playground-hub:1 Third-party cookie will be blocked. Learn more in the Issues tab.
ms-devlabs.wiql-editor.wiql-playground-hub:1 Third-party cookie will be blocked. Learn more in the Issues tab.

**Comment by AminTi** [comment]
thanks for reporting. Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors?

**Comment by TheAtomAnt** [comment]
Hi there, I went to execute this query again, and there were no issues! I don't know what has changed since I tried it this morning, but whatever the problem, it appears to be gone.

If it happens again, I will gather the additional information you requested and post it to a new ticket.
