### ISSUE TITLE
Uncaught (in promise) Invariant Violation: Minified React error #31

### ISSUE THREAD

**Issue by TheAtomAnt** [microsoft/wiql-editor#34]
Describe the bug
When running a query I see the following error message in the logs "Uncaught (in promise) Invariant Violation: Minified React error https://github.com/ostreifel/wiql-editor/issues/31"

Environment:
Updating Chrome
Version 124.0.6367.92 (Official Build) (64-bit)

Screenshots
Added file log below

To Reproduce
Run any query in the WIQL Playground

Expected behavior
Expect the query to run

Additional context
Uncaught (in promise) Invariant Violation: Minified React error https://github.com/ostreifel/wiql-editor/issues/31; visit [http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%
[dev.azure.com-1714579035942.log](https://github.com/microsoft/wiql-editor/files/15179031/dev.azure.com-1714579035942.log)
20%7BdisplayName%2C%20url%2C%20_links%2C%20id%2C%20uniqueName%2C%20imageUrl%2C%20descriptor%7D&args[]=](http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args%5B%5D=object%20with%20keys%20%7BdisplayName%2C%20url%2C%20_links%2C%20id%2C%20uniqueName%2C%20imageUrl%2C%20descriptor%7D&args%5B%5D=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at reactProdInvariant (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:401053)
at traverseAllChildrenImpl (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:403430)
at traverseAllChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:403591)
at Object.instantiateChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:317802)
at ReactDOMComponent._reconcilerInstantiateChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:363042)
at ReactDOMComponent.mountChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:363245)
at ReactDOMComponent._createInitialChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:334878)
at ReactDOMComponent.mountComponent (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:333014)
at Object.mountComponent (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:367338)
at ReactDOMComponent.mountChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:363381)

[dev.azure.com-1714579035942.log](https://github.com/ostreifel/wiql-editor/files/15179014/dev.azure.com-1714579035942.log)

**Comment by AminTi** [comment]
Hi, I just tested it, and it worked as expected. There were no errors found in the log or the network.
![Screenshot 2024-05-02 at 11 05 50](https://github.com/microsoft/wiql-editor/assets/54841342/09f40b66-e2fd-4cdc-bd00-434aef19dbf4)
Please take a screenshot of your query and post it here. Additionally, could you provide more information about your environment?

**Comment by AminTi** [comment]
Hi, if you still have the same issue take a screenshot of your query and post it here. Additionally, could you provide more information about your environment?
