### ISSUE TITLE
Results not loading in Wiql Playground when selecting certain columns in query

### ISSUE THREAD

**Issue by bart029** [microsoft/wiql-editor#35]
**Describe the bug**
We are getting a "Loading Workitems..." message with no results returned when we attempt to execute a query where we select the following columns:

- System.Id
- Custom.TargetCompletionDatee

**Environment:**
 - Browser = Chrome and Firefox
 -  hosted (Azure Devops)
 - Installed version:  2.1.69 (Latest)

**Screenshots**
![image](https://github.com/microsoft/wiql-editor/assets/164533884/76b4f615-3f6d-4b73-9a8d-8aaa9c8d6047)

**To Reproduce**
1. Go to Wiql playground
2. Enter the following query:  
3.  SELECT
        [System.Id],
        [System.AssignedTo],
        [System.State],
        [System.Title],
        [System.Tags],
        [System.WorkItemType]

FROM workitems
WHERE
        [System.TeamProject] = @project
        AND [System.AreaPath] UNDER 'CSG-Wk-Mgmt\RMDM\Singleview'
        AND [System.WorkItemType] = 'Bug'
        AND [System.ChangedDate] > @today - 2
ORDER BY [System.ChangedDate] DESC
4. Click Run.
5. The "Loading workitems..." message appears and stays there.  No results are returned.
6. Remove the [System.AssignedTo] line from the SELECT statement and click Run.
7. Results are now returned as expected

**Expected behavior**
Query should return results with any valid fields in the SELECT statement.

**Additional context**
Clicking on the "Open in queries" button to execute the query in ADO results in a successful query.

**Comment by AminTi** [comment]
![Screenshot 2024-05-08 at 13 50 39](https://github.com/microsoft/wiql-editor/assets/54841342/cb17d373-ed14-4c86-8e68-5ae8c76c0cb0)
Hi, I just tested it and it works as expected. Please make sure you have the correct syntax: (AND [System.AreaPath] UNDER ['CSG-Wk-Mgmt\RMDM\Singleview').

**Comment by bart029** [comment]
I'm still having the issue and the syntax appears to be correct.  As you can see in the screenshot, when I remove line 3 ([System.AssignedTo],) from my query, it runs properly:
![image](https://github.com/microsoft/wiql-editor/assets/164533884/e3df24f2-9a36-4b58-bd2e-dbc5bb6031fa)


Adding that line back in causes the query to not run and leaves me with the "Loading workitems..." message:
![image](https://github.com/microsoft/wiql-editor/assets/164533884/babbb3f9-fb33-4f2a-bf30-d6de144107d7)

**Comment by AminTi** [comment]
I think you have an error in this line
![Screenshot 2024-05-16 at 13 23 42](https://github.com/microsoft/wiql-editor/assets/54841342/c6576b5d-8c37-4ed0-b61f-a81e485b660d)

**Comment by bart029** [comment]
The area path is correct because the query runs properly when line 3 is deleted.  We have other queries that fail whenever we attempt to put [System.AssignedTo] in our SELECT statement.

**Comment by bart029** [comment]
Different area path, same results.  First picture is with [System.AssignedTo] included in the Select statement:

![image](https://github.com/microsoft/wiql-editor/assets/164533884/896b9334-4b69-47d8-84f4-1c97e2b4ccd0)


Second picture is the exact same query with [System.AssignedTo] removed:
![image](https://github.com/microsoft/wiql-editor/assets/164533884/db69eb44-2a8e-4a07-a6f1-8136d4e3625f)

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this again

**Comment by AminTi** [comment]
I need the network logs and the console output to help you. When I try the query, it works as expected for me.
Please provide these details so I can assist you better.

**Comment by bart029** [comment]
Here is the console output when I click the RUN button:

reactProdInvariant.js:29 Uncaught (in promise) Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BdisplayName%2C%20url%2C%20_links%2C%20id%2C%20uniqueName%2C%20imageUrl%2C%20descriptor%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:401053)
    at traverseAllChildrenImpl (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:403430)
    at traverseAllChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:403591)
    at Object.instantiateChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:317802)
    at ReactDOMComponent._reconcilerInstantiateChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:363042)
    at ReactDOMComponent.mountChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:363245)
    at ReactDOMComponent._createInitialChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:334878)
    at ReactDOMComponent.mountComponent (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:333014)
    at Object.mountComponent (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:367338)
    at ReactDOMComponent.mountChildren (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/wiql-editor/2.1.69/1712739365320/dist/playground.js:2:363381)

**Comment by bart029** [comment]
Any updates??

**Comment by filiptaik** [comment]
@AminTi I have the exact same issue. Can we please get an update

**Comment by pablosouza10** [comment]
Same issue, only "Loading workitem relations..."

**Comment by ugwulo** [comment]
Same issue here

![Image](https://github.com/user-attachments/assets/3c2d044c-7898-465d-a9e9-f6147ec6d35f)

**Comment by bart029** [comment]
@AminTi - can we please have an update on this issue?  This is still impacting us and based upon the comments on the ticket it appears that several others are impacted as well.

**Comment by bart029** [comment]
@AminTi - still looking for an update on this issue.  Can you please confirm if this issue is in the backlog anywhere??

**Comment by bart029** [comment]
@AminTi -  we have not seen an update on this issue in almost 9 months.  Can you please acknowledge that this is still in the backlog or provide any details??

**Comment by arogers-esc** [comment]
My team is also experiencing this issue.
- Queries with `System.AssignedTo` in the `SELECT` clause hang with "Loading workitems..."
- Removing  `System.AssignedTo` from the `SELECT` clause allows the query to execute.

**Comment by mmassey1993** [comment]
This is still happening. My query only runs successfully when I remove the [System.AssignedTo] component of my query, even though it is correct syntax.
